version: "3.9"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: password
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      ssh:
        # - devcontainer=/home/marcellmc/.ssh/devcontainer
        - default
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspaces/devcontainer
      - ${SSH_AUTH_SOCK}:/ssh-agent # Forward local machine SSH key to docker
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    # ports:
      # - "3000:3000"
    # depends_on:
    #   - db
